# Generated by Django 3.0.7 on 2020-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asbadb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='destinations',
            name='imgs',
            field=models.ImageField(upload_to='media'),
        ),
    ]
