# Generated by Django 3.0.7 on 2020-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asbadb', '0004_credentials_feed_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='questions',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
