# Generated by Django 3.0.7 on 2020-06-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asbadb', '0005_credentials_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ProfilePic',
        ),
    ]
